name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.3'
        bundler-cache: true

    - name: Build gem
      run: gem build alma.gemspec
    
    - name: Push to Test RubyGems
      uses: softprops/action-rubygems-push@v1
      with:
        api-key: ${{ secrets.RUBYGEMS_API_KEY }}
        gem: alma_rb
        gem-push-args: --host https://test.rubygems.org
